### ISSUE TITLE
bugtracker in META.yml

### ISSUE THREAD

**Issue by eserte** [toddr/YAML-Syck#46]
It seems that github is the canonical issue tracker, but the current META.yml still says it is RT: https://metacpan.org/source/TODDR/YAML-Syck-1.30/META.yml#L24

**Comment by toddr** [comment]
I've not done a release. If I don't do it this week, then I'll do it next week at YAPC.

**Comment by toddr** [comment]
Thanks! Fixed in 23b3b316
