### ISSUE TITLE
Changes file format not parseable by MetaCPAN

### ISSUE THREAD

**Issue by perlpunk** [toddr/YAML-Syck#55]
I just noticed that the link https://metacpan.org/release/YAML-Syck/ does not show the changes for the release. That's probably because MetaCPAN can't parse the Changes file. It's recommended to have a line like this
```
version date
```
for every release, instead of
```
[Changes for 1.32 - 2020-01-27]
```
See also https://github.com/perlpunk/perl5-module-meta

**Comment by toddr** [comment]
Fixed via 42fcfa1d4fb6ea700603a43b30c0b07c22a27d9b. Please re-open if I missed something.
